### ISSUE TITLE
getting 502 on submitting a query

### ISSUE THREAD

**Issue by arkokoley** [zense/stalkerGKSU#10]
I have been trying to use the instance at stalker.zense.co.in and all of my queries redirect to a error 502 from cloudflare.

**Comment by gopuvenkat** [comment]
A few issues came up after the app was deployed. These  #8 #9  are closed now.
The redeployment would be done by @vik-y

**Comment by gopuvenkat** [comment]
The project is live [here](http://stalker.zense.co.in/)
